name: New-2025-07-29-11:33am

on:
  workflow_dispatch:

jobs:
  tauri-init:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache full Cargo folder
        uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-full-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-full-

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Or your required version

      - name: Install Tauri CLI (if not already in cache)
        run: |
          if ! command -v cargo-tauri &> /dev/null; then
            cargo install tauri-cli
          else
            echo "Tauri CLI is already cached"
          fi

      - name: Initialize Tauri project
        run: |
          cargo-tauri init --ci --app-name "YouCanAlwaysGoBack" --window-title "You Can Always Go Back"
          [ -d ios ] || cargo-tauri ios init

      - name: Create iOS build
        run: cargo-tauri ios build

