name: Build Tauri App

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-tauri:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: JonasKruckenberg/tauri-build@v1.0.3
        with:
          runner: # optional
          args: # optional
          projectPath: # optional
          configPath: # optional
          target: # optional
          debug: # optional
